/*
=============================================================
1. Exploring All Columns in the Database
=============================================================
*/

select * from information_schema.columns
where table_name = 'customers';

select * from information_schema.columns
where table_name = 'products';

select * from information_schema.columns
where table_name = 'sales';

/*
=============================================================
2. Exploring the dimensions
=============================================================
*/

-- Exploring the geographical spread of customers

select distinct country from customers;

-- Exploring Products and its Categories

select distinct category, subcategory, product_name
from products
order by 1,2,3;

/*
=============================================================
3. Date Exploration
=============================================================
*/

-- Boundary of order dates

select 
min(order_date) as first_order_date,
max(order_date) as last_order_date
from sales;

-- Exploring Customers Ages

select
min(birthdate) as oldest_birthdate,
extract(year from age(min(birthdate))) as eldest_age,
max(birthdate) as youngest_birthdate,
extract(year from age(max(birthdate))) as youngest_age
from customers;

/*
=============================================================
4. Measures Exploration
=============================================================
*/

-- Finding total sales

select sum(sales_amount) as total_sales
from sales;

-- Total total items sold

select sum(quantity) as total_quantity
from sales;

-- Average selling price

select avg(price) as avg_price
from sales;

-- Total number of orders

select count(distinct order_number) as total_orders 
from sales;

-- Total number of products

select count(product_key) as total_products
from products;

-- Total number of customers

select count(customer_key) as total_customers
from customers;

-- Total number of customers who have placed order(s)

select count(distinct customer_key) as total_customers
from sales;

/*
=============================================================
5. Magnitude Analysis
=============================================================
*/

-- Total Customers by country

select
country,
count(customer_key) as total_customers
from customers
group by country
order by total_customers desc;

-- Total customers by gender

select
gender,
count(customer_key) as total_customers
from customers
group by gender
order by total_customers desc;

-- Total products by category

select
category,
count(product_key) as total_products
from products
group by category
order by total_products desc;

-- Average cost in each category

select category,
avg(cost) as avg_cost
from products
group by category
order by avg_cost desc;

-- Total revenue generated for each category

select
p.category,
sum(s.sales_amount) as total_revenue
from sales as s
left join products as p
on s.product_key = p.product_key
group by p.category
order by total_revenue desc;

-- Total revenue generated by each customer

select 
c.customer_key,
c.first_name,
c.last_name,
sum(sales_amount) as total_revenue
from sales as s
left join customers as c
on s.customer_key = c.customer_key
group by 1,2,3
order by total_revenue desc;

-- Distribution of sold products across countries

select 
c.country,
sum(s.quantity) as total_sold_items
from sales as s
left join customers as c
on s.customer_key = c.customer_key
group by c.country
order by total_sold_items desc;

/*
=============================================================
6. Ranking Analysis
=============================================================
*/

-- Top 5 sub-categories that generate the highest revenue 

select
p.subcategory,
sum(s.sales_amount) as total_revenue
from sales as s
left join products as p
on s.product_key = p.product_key
group by p.subcategory
order by total_revenue desc
limit 5;

-- Top 5 products that generate the highest revenue using Window Functions

select * from(
	select
	p.product_name,
	sum(s.sales_amount) as total_revenue,
	row_number() over(order by sum(s.sales_amount) desc) as rank_products
	from sales as s
	left join products as p
	on s.product_key = p.product_key
	group by p.product_name
	order by total_revenue desc) t
where rank_products <= 5;

-- Bottom 5 products in terms of sales

select
p.product_name,
sum(s.sales_amount) as total_revenue
from sales as s
left join products as p
on s.product_key = p.product_key
group by p.product_name
order by total_revenue
limit 5;

-- Top 3 customers who have placed fewest orders

select 
c.customer_key,
c.first_name,
c.last_name,
count(distinct order_number) as total_orders
from sales as s
left join customers as c
on s.customer_key = c.customer_key
group by 1,2,3
order by total_orders
limit 3;